<nav class="navbar navbar-expand-lg navbar-dark bg-info text-dark">
	<a class="navbar-brand" href="#">
		<img src="/assets/img/favicon.png" width="30" height="30" class="d-inline-block align-top" alt="">
		App Laboratorio
	</a>
	
	<?php if (isset($username_session) or isset($project_session) or isset($company_session)) : ?>
	<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
		<span class="navbar-toggler-icon"></span>
	</button>
	
	<div class="collapse navbar-collapse" id="navbarSupportedContent">
		
		<ul class="navbar-nav mr-auto">
		
			<?php if (isset($username_session) and isset($project_session) and isset($company_session)) : ?>
		
			<li class="nav-item dropdown active">
				<a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
					<i class="fa fa-store-alt"></i> Ventas
				</a>
				<div class="dropdown-menu" aria-labelledby="navbarDropdown">
					<a class="dropdown-item" href="/customers"><i class="fa fa-users"></i> Clientes</a>
					<div class="dropdown-divider"></div>
					<a class="dropdown-item" href="/sales"><i class="fa fa-receipt"></i> Confección de Comprobantes</a>
					<a class="dropdown-item" href="/sales/query"><i class="fa fa-search"></i> Consulta de Comprobantes</a>
					<div class="dropdown-divider"></div>
					<a class="dropdown-item" href="/sales/report"><i class="fa fa-list-ul"></i> Listado de Ventas</a>
				</div>
			</li>
			
			<?php endif; ?>
			
		</ul>
		
		<?php if (isset($username_session) or isset($project_session) or isset($company_session)) : ?>
		<form class="form-inline my-2 my-lg-0 mr-3">
			<ul class="navbar-nav mr-auto">
				
				<?php if (isset($project_session)) : ?>
				<li class="nav-item dropdown active">
					<a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
						<i class="fa fa-home"></i> <?= $project_session ?>
					</a>
					<div class="dropdown-menu" aria-labelledby="navbarDropdown">
						<a class="dropdown-item" href="#"><i class="fa fa-edit"></i> Editar Proyecto</a>
						<a class="dropdown-item" href="#"><i class="fa fa-envelope"></i> Invitar usuarios</a>
						<div class="dropdown-divider"></div>
						<a class="dropdown-item" href="/login/projects/selection"><i class="fa fa-retweet"></i> Elegir otro Proyecto</a>
					</div>
				</li>
				<?php endif; ?>
				
				<?php if (isset($company_session)) : ?>
				<li class="nav-item dropdown active">
					<a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
						<i class="fa fa-building"></i> <?= $company_session ?>
					</a>
					<div class="dropdown-menu" aria-labelledby="navbarDropdown">
						<a class="dropdown-item" href="/login/companies/selection"><i class="fa fa-retweet"></i> Elegir otra Compañía</a>
					</div>
				</li>
				<?php endif; ?>
				
				<?php if (isset($display_name_session)) : ?>
				<li class="nav-item dropdown active">
					<a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
						<i class="fa fa-user-check"></i> <?= $display_name_session ?>
					</a>
					<div class="dropdown-menu" aria-labelledby="navbarDropdown">
						<a class="dropdown-item" href="#"><i class="fa fa-edit"></i> Editar perfil</a>
						<div class="dropdown-divider"></div>
						<a class="dropdown-item" href="#" name="btnLogout"><i class="fa fa-times"></i> Cerrar sesión</a>
					</div>
				</li>
				<?php endif; ?>
				
			</ul>
		</form>
		<?php endif; ?>
		
	</div>
	<?php endif; ?>
	
</nav>