<!doctype html>
<html lang="en">
	<head>
		<?= $this->fetch('/partials/header.phtml') ?>
	</head>
	<body>
		<?= $this->fetch('/partials/navbar.phtml', $navbar) ?>
		
		<?php $customers_enabled 			= (isset($customers) and count($customers) > 0); ?>
		<?php $salesDocsTypes_enabled		= (isset($salesDocsTypes) and count($salesDocsTypes) > 0); ?>
		
		<div class="container-fluid">
			<div class="content">
				<div class="row">
					<div class="col-12 p-0">
						<div class="card card-no-rounded" style="height:100%">
							<div class="card-header d-flex justify-content-between">
								<span><b><i class="fa fa-list-ul"></i> Listado de Ventas</b></span>
							</div>
							<div class="card-body">
								
								<div class="row">
									<div class="col-lg-4 col-md-6">
										<div class="form-group">
											<label class="font-weight-bold">Clientes:</label>
											<br>
											<label <?= !$customers_enabled ? '' : 'class="d-none" ' ?>name="customers-label"><i class="fa fa-exclamation-triangle"></i> No hay clientes disponibles!</label>
											<select class="form-control<?= $customers_enabled ? '' : ' d-none' ?>" name="customers-select" multiple="multiple">
											<?php if ($customers_enabled) : ?>
											<?php foreach($customers as $customer) : ?>
												<option value="<?= $customer->id ?>">
													<?= $customer->business_name ?>
												</option>
											<?php endforeach; ?>
											<?php endif; ?>
											</select>
										</div>
									</div>
								
									<?php if (false) : ?>
									<div class="col-lg-4 col-md-6">
										<div class="form-group">
											<label class="font-weight-bold">Comp. de Ventas:</label>
											<div class="form-check form-check-inline">
												<input class="form-check-input" type="checkbox" name="sales-docs-types-check-nothing">
												<label class="form-check-label">Ninguno</label>
											</div>
											<br>
											<label <?= !$salesDocsTypes_enabled ? '' : 'class="d-none" ' ?>name="sales-docs-types-label"><i class="fa fa-exclamation-triangle"></i> No hay documentos disponibles!</label>
											<select class="form-control<?= $salesDocsTypes_enabled ? '' : ' d-none' ?>" name="sales-docs-types-select" multiple="multiple">
											<?php if ($salesDocsTypes_enabled) : ?>
											<?php foreach($salesDocsTypes as $documentType) : ?>
												<option
													value="<?= $documentType->unique_code ?>">
													<?= trim($documentType->description) ?>
												</option>
											<?php endforeach; ?>
											<?php endif; ?>
											</select>
										</div>
									</div>
											<?php endif; ?>

									<div class="col-lg-4 col-md-6">
										<div class="form-group">
											<label class="font-weight-bold">Fecha:</label>
											<input class="form-control" type="date" name="dated-at">
										</div>
									</div>
								</div>
								
								<div class="row">
							        <div class="col">
										<span class="btn btn-outline-primary pr-2" name="btn-report"><i class="fa fa-list-ul"></i> Generar Reporte</span>
										<span class="btn btn-outline-primary" name="btn-export"><i class="fa fa-file-excel"></i> Exportar a Excel</span>
									</div>
								</div>
								
								<hr>
									
							    <div class="row mt-3">
							        <div class="col">
							            <div name="report-content" class="table-responsive small">
											<table id="table_report" name="table-report" class="table table-striped table-bordered table-hover table-sm">
												<thead class="thead-dark">
													<tr>
														<th>Fecha</th>
														<th>Hora</th>
														<th>Veterinaria</th>
														<th>Domicilio</th>
														<th>Vendedor</th>
														<th>Localidad</th>
														<th>Telefono</th>
														<th>Med. Veterinario</th>
														<th>Productos que trabajan</th>
														<th>Email</th>
													</tr>
												</thead>
												<tbody>
												</tbody>
											</table>
										</div>
							        </div>
							    </div>
							</div>
						</div>
					</div>
				</div>
				
			</div>
		</div>
			
		<?= $this->fetch('/partials/libs.phtml') ?>
		
		<!-- Optional JavaScript -->
		<script>
			$(function()
			{
				if ( !$('select[name="customers-select"]').hasClass('d-none') )
					$('select[name="customers-select"]').select2({ width: '100%' });
				
				if ( !$('select[name="sales-docs-types-select"]').hasClass('d-none') )
					$('select[name="sales-docs-types-select"]').select2({ width: '100%' });
				
				// click on report
				$('span[name="btn-report"]').on('click', function(e) {
					e.preventDefault();
					
					var salesDocsCodes = ['x'];
					if ( !$('input[name="sales-docs-types-check-nothing"]').prop('checked') ) {
						salesDocsCodes = $('select[name="sales-docs-types-select"]').val();
					}
					
					$.ajax({
						method: 'POST',
						url: '/sales/report',
						data: { 
							customers_ids : 	$('select[name="customers-select"]').val(),
							sales_docs_codes : 	salesDocsCodes,
							dated_at :			$('input[name="dated-at"]').val(),
						},
						success: function(data, textStatus, jqXHR)
						{
							if (data.Result == 'OK')
							{
								var body = $('div[name="report-content"] > table[name="table-report"] > tbody');
								
								body.empty();

								data.Records.forEach(function(record) {
									body.append("<tr>" +
													"<td>" + record.dated_at + "</td>" +
													"<td>" + record.timed_at + "</td>" +
													"<td>" + record.business_name + "</td>" +
													"<td>Dir: " + record.location + "</td>" +
													"<td>Jose Boccuzzi</td>" +
													"<td>CAP</td>" +
													"<td>" + record.phone_number + "</td>" +
													"<td>" + record.contact_name + "</td>" +
													"<td>" + record.comments + "</td>" +
													"<td>" + record.email + "</td>" +
												"</tr>");
								});
								
							}
							else {
								alert('error');
							}
						},
						error: function(jqXHR, textStatus, errorThrown) {
							console.warn(jqXHR.responseText);
						},
					});
				});

				// click on export
				$('span[name="btn-export"]').on('click', function(e) {
					e.preventDefault();
					exportTableToExcel('table_report');
				});

				// click on send email
				$('span[name="btn-email"]').on('click', function(e) {
					e.preventDefault();
					
					$.ajax({
						method: 'POST',
						url: '/sales/email',
						data: {},
						success: function(data, textStatus, jqXHR)
						{
							if (data.Result == 'OK')
							{
								alert('ok');
							}
							else {
								alert('error');
							}
						},
						error: function(jqXHR, textStatus, errorThrown) {
							console.warn(jqXHR.responseText);
						},
					});
				});
				
				// checkboxes
				$('input[name="sales-docs-types-check-nothing"]').on('change', function(e) {
					var checked = $(this).prop('checked');
					$('select[name="sales-docs-types-select"]').prop("disabled", checked);
				});

				// export to excel
				function exportTableToExcel(tableID)
				{
					var table = TableExport(document.getElementById(tableID));

					var exportData = table.getExportData(); 
					var xlsxData = exportData.table_report.xlsx; // Replace with the kind of file you want from the exportData
					table.export2file(xlsxData.data, xlsxData.mimeType, xlsxData.filename, xlsxData.fileExtension, xlsxData.merges, xlsxData.RTL, xlsxData.sheetname);
				}

				/*function exportTableToExcel(tableID, filename = ''){
					var downloadLink;
					var dataType = 'application/vnd.ms-excel';
					var tableSelect = document.getElementById(tableID);
					var tableHTML = tableSelect.outerHTML.replace(/ /g, '%20');
					
					// Specify file name
					filename = filename?filename+'.xls':'excel_data.xls';
					
					// Create download link element
					downloadLink = document.createElement("a");
					
					document.body.appendChild(downloadLink);
					
					if(navigator.msSaveOrOpenBlob){
						var blob = new Blob(['\ufeff', tableHTML], {
							type: dataType
						});
						navigator.msSaveOrOpenBlob( blob, filename);
					}else{
						// Create a link to the file
						downloadLink.href = 'data:' + dataType + ', ' + tableHTML;
					
						// Setting the file name
						downloadLink.download = filename;
						
						//triggering the function
						downloadLink.click();
					}
				}*/

			});
		</script>
	</body>
</html>