<!doctype html>
<html lang="en">
	<head>
		<?= $this->fetch('/partials/header.phtml') ?>
	</head>
	<body>
		<?= $this->fetch('/partials/navbar.phtml', $navbar) ?>
		
		<?= $this->fetch('/partials/toolbar.phtml', $navbar) ?>
		
		<?php $customers_enabled 		= (isset($customers) and count($customers) > 0); ?>
		<?php $documentsTypes_enabled	= (isset($documentsTypes) and count($documentsTypes) > 0); ?>
		
		<div class="container-fluid">
			<div class="content">
				<div class="row">
					<div class="col-12 p-0">
						<div class="card card-no-rounded">
							<div class="card-header d-flex justify-content-between align-items-center">
								<span><b><i class="fa fa-receipt"></i> Ventas <i class="fa fa-chevron-right"></i> <?= ((isset($headerId) and $headerId > 0) ? "Edición de Comprobante #" . $headerId : "Confección de Comprobante") ?></b></span>
							</div>
							
							<?php if (isset($headerId) and $headerId > 0) : ?>
							<data name="document-data" data-header-id="<?= $headerId ?>"></data>
							<?php endif; ?>
							
							<div class="card-body">
								
								<div class="row">
									<div class="col-lg-3 col-md-6">
										<div class="form-group">
											<label class="font-weight-bold">Cliente:</label>
											<br>
											<label <?= !$customers_enabled ? '' : 'class="d-none" ' ?>name="customers-label"><i class="fa fa-exclamation-triangle"></i> No hay clientes disponibles!</label>
											<select class="form-control<?= $customers_enabled ? '' : ' d-none' ?>" name="customers-select">
											<?php if ($customers_enabled) : ?>
												<option value="N/A">Seleccionar cliente...</option>
											<?php foreach($customers as $customer) : ?>
												<option value="<?= $customer->id ?>">
													<?= $customer->business_name ?>
												</option>
											<?php endforeach; ?>
											<?php endif; ?>
											</select>
										</div>
									</div>
									
									<?php if (false) : ?>
									<div class="col-lg-3 col-md-6">
										<div class="form-group">
											<label class="font-weight-bold">Comprobante:</label>
											<br>
											<label <?= !$documentsTypes_enabled ? '' : 'class="d-none" ' ?>name="docs-types-label"><i class="fa fa-exclamation-triangle"></i> No hay documentos disponibles!</label>
											<select class="form-control<?= $documentsTypes_enabled ? '' : ' d-none' ?>" name="docs-types-select">
											<?php if ($documentsTypes_enabled) : ?>
												<option value="N/A">Seleccionar documento...</option>
											<?php foreach($documentsTypes as $documentType) : ?>
												<option
													value="<?= $documentType->unique_code ?>"
													data-sequence="<?= $documentType->sequence ?>"
													<?= ($documentType->is_default ? " selected" : "") ?>
													>
													<?= trim($documentType->description) ?>
												</option>
											<?php endforeach; ?>
											<?php endif; ?>
											</select>
										</div>
									</div>
									<?php endif; ?>
									
									<div class="col-lg-3 col-md-6">
										<div class="form-group">
											<label class="font-weight-bold">Fecha:</label>
											<br>
											<input type="datetime-local" class="form-control" name="doc-date" />
										</div>
									</div>
								</div>
								
								<hr />
								<div class="row mt-2">
									<div class="col">
										<div class="form-group">
											<label class="font-weight-bold">Observaciones:</label>
											<br>
											<textarea class="form-control" name="doc-comments" rows="6"></textarea>
										</div>
									</div>
								</div>
								
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
		
		<?= $this->fetch('/partials/libs.phtml') ?>
		
		<!-- Optional JavaScript -->
		<script>
			$(function(){
				
				// ***************************** //
				// ** DOCUMENT INITIALIZATION ** //
				// ***************************** //
				
				// block UI on every ajax
				$(document)
					.ajaxStart(function() {
						$.blockUI({ message : null });
					})
					.ajaxStop(function() {
						$.unblockUI();
					});
				
				// create viewports
				$("body").append('<div class="device-xs d-block d-sm-none"></div>');
				$("body").append('<div class="device-sm d-none d-sm-block d-md-none"></div>');
				$("body").append('<div class="device-md d-none d-md-block d-lg-none"></div>');
				$("body").append('<div class="device-lg d-none d-lg-block d-xl-none"></div>');
				$("body").append('<div class="device-xl d-none d-xl-block"></div>');
				
				setupSelects();
				
				initializeDocument();
				
				// ********************* //
				// ** DOCUMENT EVENTS ** //
				// ********************* //
								
				// on before unload
				$(window).on('beforeunload', function() {
					if (hasUnsavedChanges())
						return "Hay cambios no guardados, ¿desea salir de todas maneras?";
				});
				
				// toolbar actions
				$('#btn-toolbar-save').click(function(e) {
					e.preventDefault();
					saveDocument();
				});
				
				// ************************ //
				// ** DOCUMENT FUNCTIONS ** //
				// ************************ //
				
				// check viewport
				function isBreakpoint(alias) {
					return $('.device-' + alias).is(':visible');
				}				
				
				function setupSelects() {
					// customers
					if ( !$('select[name="customers-select"]').hasClass('d-none') )
						$('select[name="customers-select"]').select2({ width : '100%' }); // .chosen({ max_shown_results : 6, width : "100%" });
					
					// documents types
					if ( !$('select[name="docs-types-select"]').hasClass('d-none') )
						$('select[name="docs-types-select"]').select2({ width : '100%' });
				}
				
				function saveDocument() {
					
					if (validateDocument())
					{
						var documentData = {
							customer_id : 			$('select[name="customers-select"] option:selected').val(),
							document_type_code : 	$('select[name="docs-types-select"] option:selected').val(),
							dated_at : 				$('input[name="doc-date"]').val(),
							comments : 				$('textarea[name="doc-comments"]').val(),
						};
						
						if (isEdit())
						{
							documentData["id"] = getHeaderId();
						}

						$.ajax({
							method: 'POST',
							url: '/sales/' + (isEdit() ? 'update' : 'create'),
							dataType: 'json',
							data: documentData,
							success: function(data, textStatus, jqXHR)
							{
								if (data.status == 'OK')
								{
									$.stdShowMessage({
										icon: 'fa fa-check',
										message: data.message,
										type: 'info'
									});
									
									if (!isEdit())
									{
									    resetDocument(documentData);
									}
								}
								else {
									alert('error');
								}
							},
							error: function(jqXHR, textStatus, errorThrown) {
								console.warn(jqXHR.responseText);
							},
						});
					}				
				}
				
				function validateDocument() {
					var message = "<b>Documento no guardado:</b>";
					var error = false;
					
					if ( $('select[name="customers-select"]').val() == "N/A"
						|| $('select[name="customers-select"]').hasClass("d-none") ) {
						message += "<br>Debe seleccionar un cliente";
						error = true;
					}
					
					if ( $('select[name="docs-types-select"]').val() == "N/A"
						|| $('select[name="docs-types-select"]').hasClass("d-none") ) {
						message += "<br>Debe seleccionar un documento";
						error = true;
					}
					
					if (error) {
						$.stdShowMessage({
							icon: 'fa fa-exclamation-triangle',
							message: message,
							type: 'warning'
						});
					}
					
					return !error;
				}
				
				function resetDocument(data)
				{
					$('select[name="customers-select"]').val('N/A').trigger('change');
					$('select[name="docs-types-select"]').val('N/A').trigger('change');
					$('input[name="doc-date"]').val("");
					
					$('textarea[name="doc-comments"]').val("");
				}
				
				function hasUnsavedChanges()
				{
					if ( $('select[name="customers-select"]').val() != 'N/A' )
						return true;
					
					if ( $('select[name="docs-types-select"]').val() != 'N/A' )
						return true;
					
					if ( $('input[name="doc-date"]').val() != "" )
						return true;
					
					return false;
				}
				
				function initializeDocument()
				{
					if (isEdit())
					{
						var headerId = getHeaderId();
						
						$.ajax({
							method: 'POST',
							url: '/sales/one/' + headerId,
							success: function(data, textStatus, jqXHR)
							{
								if (data.Result == 'OK')
								{
									// header
									$('select[name="customers-select"]').val(data.Document.customer_id).trigger('change');
									$('select[name="docs-types-select"]').val(data.Document.document_type_code).trigger('change');
									$('input[name="doc-date"]').val(data.Document.dated_at.replace(" ", "T"));
									
									// footer
									$('textarea[name="doc-comments"]').val(data.Document.comments);
								}
								else if (data.Result == 'ERROR') {
									$.stdShowMessage({
										icon: 'fa fa-exclamation-triangle',
										message: data.Message,
										type: 'info'
									});
								}
							},
							error: function(jqXHR, textStatus, errorThrown) {
								console.warn(jqXHR.responseText);
							},
						});
					}
				}
				
				function isEdit()
				{
					return $("data[name='document-data']").length > 0 && $("data[name='document-data']").attr("data-header-id") > 0;
				}
				
				function getHeaderId()
				{
					return $("data[name='document-data']").attr("data-header-id");
				}
				
			});
		</script>
	</body>
</html>